"""Curated quiz question bank across multiple categories."""

CATEGORIES = [
    {"id": "general", "name": "General Knowledge", "icon": "Globe", "color": "#E4FF00",
     "image": "https://images.unsplash.com/photo-1534515538060-80212d73acb6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzV8MHwxfHNlYXJjaHwzfHxuZW9uJTIwM2QlMjByZW5kZXJ8ZW58MHx8fHwxNzgyNzI3NjA3fDA&ixlib=rb-4.1.0&q=85"},
    {"id": "science", "name": "Science", "icon": "Atom", "color": "#00F0FF",
     "image": "https://images.unsplash.com/photo-1557264322-b44d383a2906?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNDR8MHwxfHNlYXJjaHwxfHxuZW9uJTIwYWJzdHJhY3QlMjBkYXJrfGVufDB8fHx8MTc4NTM5MDczNXww&ixlib=rb-4.1.0&q=85"},
    {"id": "sports", "name": "Sports", "icon": "SoccerBall", "color": "#00FF66",
     "image": "https://images.pexels.com/photos/33911793/pexels-photo-33911793.jpeg"},
    {"id": "movies", "name": "Movies & TV", "icon": "FilmSlate", "color": "#FF0055",
     "image": "https://images.pexels.com/photos/13800328/pexels-photo-13800328.jpeg"},
    {"id": "tech", "name": "Tech & Gaming", "icon": "GameController", "color": "#E4FF00",
     "image": "https://images.pexels.com/photos/7915213/pexels-photo-7915213.jpeg"},
    {"id": "history", "name": "History", "icon": "Scroll", "color": "#FF0055",
     "image": "https://images.unsplash.com/photo-1534515538060-80212d73acb6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzV8MHwxfHNlYXJjaHwzfHxuZW9uJTIwM2QlMjByZW5kZXJ8ZW58MHx8fHwxNzgyNzI3NjA3fDA&ixlib=rb-4.1.0&q=85"},
    {"id": "music", "name": "Music", "icon": "MusicNote", "color": "#00F0FF",
     "image": "https://images.unsplash.com/photo-1534515538060-80212d73acb6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzV8MHwxfHNlYXJjaHwzfHxuZW9uJTIwM2QlMjByZW5kZXJ8ZW58MHx8fHwxNzgyNzI3NjA3fDA&ixlib=rb-4.1.0&q=85"},
    {"id": "geography", "name": "Geography", "icon": "MapTrifold", "color": "#00FF66",
     "image": "https://images.pexels.com/photos/33911793/pexels-photo-33911793.jpeg"},
]

# 15 questions per category (10 randomly picked per quiz)
QUESTIONS = {
    "general": [
        {"q": "What is the capital of Australia?", "opts": ["Sydney", "Melbourne", "Canberra", "Perth"], "a": 2},
        {"q": "How many continents are there on Earth?", "opts": ["5", "6", "7", "8"], "a": 2},
        {"q": "What is the largest ocean in the world?", "opts": ["Atlantic", "Indian", "Arctic", "Pacific"], "a": 3},
        {"q": "Which language has the most native speakers worldwide?", "opts": ["English", "Spanish", "Mandarin Chinese", "Hindi"], "a": 2},
        {"q": "What currency is used in Japan?", "opts": ["Yuan", "Won", "Yen", "Ringgit"], "a": 2},
        {"q": "Which is the smallest country in the world?", "opts": ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], "a": 1},
        {"q": "What is the tallest mountain in the world?", "opts": ["K2", "Mount Everest", "Kangchenjunga", "Makalu"], "a": 1},
        {"q": "How many colors are in a rainbow?", "opts": ["5", "6", "7", "8"], "a": 2},
        {"q": "Which planet is known as the Red Planet?", "opts": ["Venus", "Mars", "Jupiter", "Saturn"], "a": 1},
        {"q": "What is the longest river in the world?", "opts": ["Amazon", "Nile", "Yangtze", "Mississippi"], "a": 1},
        {"q": "Which country invented pizza?", "opts": ["France", "Italy", "Greece", "Spain"], "a": 1},
        {"q": "What is the hardest natural substance on Earth?", "opts": ["Gold", "Iron", "Diamond", "Quartz"], "a": 2},
        {"q": "Which sea creature has three hearts?", "opts": ["Shark", "Octopus", "Whale", "Dolphin"], "a": 1},
        {"q": "What does 'www' stand for in a website browser?", "opts": ["World Wide Web", "World Wide Wire", "Web Wide World", "Wide Web World"], "a": 0},
        {"q": "How many bones are in the adult human body?", "opts": ["186", "206", "226", "246"], "a": 1},
    ],
    "science": [
        {"q": "What is the chemical symbol for gold?", "opts": ["Go", "Gd", "Au", "Ag"], "a": 2},
        {"q": "What is the speed of light in vacuum (approx)?", "opts": ["3×10^5 km/s", "3×10^6 km/s", "3×10^7 km/s", "3×10^8 m/s"], "a": 3},
        {"q": "Which gas do plants absorb from the atmosphere?", "opts": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "a": 2},
        {"q": "What is H2O commonly known as?", "opts": ["Salt", "Water", "Hydrogen", "Oxygen"], "a": 1},
        {"q": "How many planets are in our solar system?", "opts": ["7", "8", "9", "10"], "a": 1},
        {"q": "What force keeps us on the ground?", "opts": ["Magnetism", "Gravity", "Friction", "Inertia"], "a": 1},
        {"q": "What is the smallest unit of matter?", "opts": ["Molecule", "Atom", "Cell", "Electron"], "a": 1},
        {"q": "Which organ pumps blood in the human body?", "opts": ["Liver", "Lungs", "Heart", "Kidney"], "a": 2},
        {"q": "What is the boiling point of water in Celsius?", "opts": ["90°", "100°", "110°", "120°"], "a": 1},
        {"q": "Who developed the theory of general relativity?", "opts": ["Newton", "Einstein", "Bohr", "Hawking"], "a": 1},
        {"q": "What is the largest planet in our solar system?", "opts": ["Saturn", "Neptune", "Jupiter", "Uranus"], "a": 2},
        {"q": "Which vitamin does the body produce from sunlight?", "opts": ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], "a": 3},
        {"q": "What is DNA short for?", "opts": ["Deoxyribonucleic Acid", "Dinucleic Acid", "Deoxyribose Nitrate", "Dual Nucleic Acid"], "a": 0},
        {"q": "What is the pH of pure water?", "opts": ["5", "6", "7", "8"], "a": 2},
        {"q": "What element has the atomic number 1?", "opts": ["Helium", "Oxygen", "Hydrogen", "Carbon"], "a": 2},
    ],
    "sports": [
        {"q": "How many players are on a soccer field per team?", "opts": ["9", "10", "11", "12"], "a": 2},
        {"q": "In which sport is 'Grand Slam' a term?", "opts": ["Football", "Tennis", "Cricket", "Golf"], "a": 1},
        {"q": "How often are the Olympic Games held?", "opts": ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], "a": 2},
        {"q": "What is the maximum score in a single frame of bowling?", "opts": ["10", "20", "30", "40"], "a": 2},
        {"q": "Who has won the most FIFA Ballon d'Or awards?", "opts": ["Ronaldo", "Messi", "Maradona", "Pelé"], "a": 1},
        {"q": "In basketball, how many points is a free throw worth?", "opts": ["1", "2", "3", "4"], "a": 0},
        {"q": "Which country invented the sport of cricket?", "opts": ["India", "Australia", "England", "South Africa"], "a": 2},
        {"q": "What color card in soccer means a player is sent off?", "opts": ["Yellow", "Red", "Blue", "Green"], "a": 1},
        {"q": "How many rings are on the Olympic flag?", "opts": ["4", "5", "6", "7"], "a": 1},
        {"q": "Which sport uses a shuttlecock?", "opts": ["Tennis", "Table Tennis", "Badminton", "Squash"], "a": 2},
        {"q": "In which sport would you perform a slam dunk?", "opts": ["Volleyball", "Basketball", "Netball", "Handball"], "a": 1},
        {"q": "Who is the all-time leading NBA scorer?", "opts": ["Michael Jordan", "Kobe Bryant", "LeBron James", "Kareem Abdul-Jabbar"], "a": 2},
        {"q": "How long is a marathon (approx)?", "opts": ["26.2 miles", "20 miles", "30 miles", "13.1 miles"], "a": 0},
        {"q": "Which country has won the most FIFA World Cups?", "opts": ["Germany", "Argentina", "Brazil", "Italy"], "a": 2},
        {"q": "What is the diameter of a basketball hoop (inches)?", "opts": ["16", "18", "20", "22"], "a": 1},
    ],
    "movies": [
        {"q": "Who directed the movie 'Inception'?", "opts": ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Quentin Tarantino"], "a": 1},
        {"q": "Which movie features the character 'Jack Dawson'?", "opts": ["Titanic", "Avatar", "The Revenant", "Gladiator"], "a": 0},
        {"q": "Who played the Joker in 'The Dark Knight' (2008)?", "opts": ["Jared Leto", "Joaquin Phoenix", "Heath Ledger", "Jack Nicholson"], "a": 2},
        {"q": "Which movie has the quote 'May the Force be with you'?", "opts": ["Star Trek", "Star Wars", "Interstellar", "Guardians of the Galaxy"], "a": 1},
        {"q": "How many Harry Potter films are there?", "opts": ["6", "7", "8", "9"], "a": 2},
        {"q": "Which movie won Best Picture at the 2020 Oscars?", "opts": ["1917", "Parasite", "Joker", "Once Upon a Time in Hollywood"], "a": 1},
        {"q": "Who plays Tony Stark in the MCU?", "opts": ["Chris Evans", "Robert Downey Jr.", "Mark Ruffalo", "Chris Hemsworth"], "a": 1},
        {"q": "What is the highest-grossing film of all time (unadjusted)?", "opts": ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars: The Force Awakens"], "a": 2},
        {"q": "Which animated film features 'Let It Go'?", "opts": ["Moana", "Tangled", "Frozen", "Encanto"], "a": 2},
        {"q": "In 'The Matrix', what color pill does Neo take?", "opts": ["Blue", "Red", "Green", "Yellow"], "a": 1},
        {"q": "Who directed 'Pulp Fiction'?", "opts": ["Martin Scorsese", "Quentin Tarantino", "Coen Brothers", "David Fincher"], "a": 1},
        {"q": "Which movie is Forrest Gump's occupation associated with?", "opts": ["Shrimp Boat Captain", "Truck Driver", "Bus Driver", "Pilot"], "a": 0},
        {"q": "'Breaking Bad' is set in which US state?", "opts": ["Arizona", "New Mexico", "Nevada", "Texas"], "a": 1},
        {"q": "Which show features the Iron Throne?", "opts": ["The Witcher", "Vikings", "Game of Thrones", "The Last Kingdom"], "a": 2},
        {"q": "Who plays Wolverine in the X-Men films?", "opts": ["Hugh Jackman", "Ryan Reynolds", "Michael Fassbender", "James McAvoy"], "a": 0},
    ],
    "tech": [
        {"q": "Who founded Microsoft?", "opts": ["Steve Jobs", "Bill Gates", "Elon Musk", "Larry Page"], "a": 1},
        {"q": "What does CPU stand for?", "opts": ["Central Processing Unit", "Computer Personal Unit", "Central Program Unit", "Control Processing Unit"], "a": 0},
        {"q": "Which company created the iPhone?", "opts": ["Samsung", "Apple", "Google", "Nokia"], "a": 1},
        {"q": "What year was YouTube founded?", "opts": ["2003", "2005", "2007", "2009"], "a": 1},
        {"q": "Who is the CEO of Tesla?", "opts": ["Jeff Bezos", "Elon Musk", "Tim Cook", "Sundar Pichai"], "a": 1},
        {"q": "What does HTTP stand for?", "opts": ["HyperText Transfer Protocol", "HyperText Transport Protocol", "High Transfer Text Protocol", "Home Tool Transfer Protocol"], "a": 0},
        {"q": "Which game is developed by Mojang?", "opts": ["Fortnite", "Roblox", "Minecraft", "Valorant"], "a": 2},
        {"q": "Which company owns the game engine 'Unreal Engine'?", "opts": ["Unity Tech", "Epic Games", "Valve", "Blizzard"], "a": 1},
        {"q": "What is the name of Nintendo's iconic plumber?", "opts": ["Luigi", "Wario", "Mario", "Toad"], "a": 2},
        {"q": "What year was the first iPhone released?", "opts": ["2005", "2007", "2009", "2011"], "a": 1},
        {"q": "What does 'AI' stand for?", "opts": ["Automatic Intelligence", "Artificial Intelligence", "Applied Intelligence", "Advanced Interface"], "a": 1},
        {"q": "Which company created the ChatGPT AI?", "opts": ["Google", "Meta", "OpenAI", "Microsoft"], "a": 2},
        {"q": "Which console is made by Sony?", "opts": ["Xbox", "Switch", "PlayStation", "Steam Deck"], "a": 2},
        {"q": "What language runs in a web browser?", "opts": ["Python", "Java", "C++", "JavaScript"], "a": 3},
        {"q": "In which game do you say 'GG'?", "opts": ["Chess", "Any competitive game", "Cricket", "Golf"], "a": 1},
    ],
    "history": [
        {"q": "In which year did World War II end?", "opts": ["1943", "1944", "1945", "1946"], "a": 2},
        {"q": "Who was the first President of the United States?", "opts": ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"], "a": 1},
        {"q": "The Great Wall of China was built primarily to defend against?", "opts": ["Mongols", "Japanese", "Russians", "Vietnamese"], "a": 0},
        {"q": "Which empire built the Colosseum?", "opts": ["Greek", "Roman", "Egyptian", "Persian"], "a": 1},
        {"q": "Who painted the Mona Lisa?", "opts": ["Michelangelo", "Raphael", "Da Vinci", "Van Gogh"], "a": 2},
        {"q": "In which year did the Titanic sink?", "opts": ["1905", "1912", "1918", "1925"], "a": 1},
        {"q": "Who was known as the 'Iron Lady'?", "opts": ["Angela Merkel", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"], "a": 1},
        {"q": "The Berlin Wall fell in which year?", "opts": ["1987", "1989", "1991", "1993"], "a": 1},
        {"q": "Who discovered America in 1492?", "opts": ["Vasco da Gama", "Columbus", "Magellan", "Cook"], "a": 1},
        {"q": "Which ancient civilization built the pyramids of Giza?", "opts": ["Aztec", "Mayan", "Egyptian", "Sumerian"], "a": 2},
        {"q": "Who was the leader of the Soviet Union during WWII?", "opts": ["Lenin", "Stalin", "Khrushchev", "Gorbachev"], "a": 1},
        {"q": "The French Revolution began in which year?", "opts": ["1776", "1789", "1804", "1815"], "a": 1},
        {"q": "Which war was fought between the North and South in the USA?", "opts": ["Revolutionary War", "Civil War", "War of 1812", "Cold War"], "a": 1},
        {"q": "Who was the last Mughal Emperor?", "opts": ["Akbar", "Aurangzeb", "Bahadur Shah II", "Shah Jahan"], "a": 2},
        {"q": "Julius Caesar was assassinated in which year?", "opts": ["44 BC", "27 BC", "14 AD", "100 BC"], "a": 0},
    ],
    "music": [
        {"q": "Who is known as the King of Pop?", "opts": ["Elvis Presley", "Michael Jackson", "Prince", "Justin Bieber"], "a": 1},
        {"q": "How many strings does a standard guitar have?", "opts": ["4", "5", "6", "7"], "a": 2},
        {"q": "Which band sang 'Bohemian Rhapsody'?", "opts": ["The Beatles", "Queen", "Led Zeppelin", "Pink Floyd"], "a": 1},
        {"q": "Who sang 'Shape of You'?", "opts": ["Bruno Mars", "Ed Sheeran", "The Weeknd", "Justin Bieber"], "a": 1},
        {"q": "Which instrument has 88 keys?", "opts": ["Organ", "Piano", "Harpsichord", "Accordion"], "a": 1},
        {"q": "Who is the lead singer of Coldplay?", "opts": ["Chris Martin", "Bono", "Mick Jagger", "Freddie Mercury"], "a": 0},
        {"q": "Which country did K-Pop originate?", "opts": ["Japan", "China", "South Korea", "Thailand"], "a": 2},
        {"q": "Which artist released the album '1989'?", "opts": ["Adele", "Taylor Swift", "Beyoncé", "Katy Perry"], "a": 1},
        {"q": "Who composed 'Für Elise'?", "opts": ["Mozart", "Beethoven", "Bach", "Chopin"], "a": 1},
        {"q": "Which rapper's real name is Marshall Mathers?", "opts": ["Jay-Z", "Eminem", "Drake", "Kanye West"], "a": 1},
        {"q": "'Rolling in the Deep' is sung by?", "opts": ["Sia", "Adele", "Rihanna", "Lady Gaga"], "a": 1},
        {"q": "Which BTS song was their first US number 1?", "opts": ["Dynamite", "Butter", "Boy With Luv", "DNA"], "a": 0},
        {"q": "The Beatles are from which UK city?", "opts": ["London", "Manchester", "Liverpool", "Birmingham"], "a": 2},
        {"q": "Which song made Psy internationally famous?", "opts": ["Gangnam Style", "Gentleman", "Daddy", "New Face"], "a": 0},
        {"q": "Who is the 'Queen of Pop'?", "opts": ["Madonna", "Cher", "Britney Spears", "Whitney Houston"], "a": 0},
    ],
    "geography": [
        {"q": "What is the largest desert in the world?", "opts": ["Sahara", "Gobi", "Antarctic Desert", "Kalahari"], "a": 2},
        {"q": "Mount Fuji is located in?", "opts": ["China", "Japan", "Korea", "Nepal"], "a": 1},
        {"q": "Which country is home to the kangaroo?", "opts": ["New Zealand", "Australia", "South Africa", "India"], "a": 1},
        {"q": "The Amazon rainforest is primarily in which country?", "opts": ["Peru", "Colombia", "Brazil", "Venezuela"], "a": 2},
        {"q": "What is the capital of Canada?", "opts": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "a": 2},
        {"q": "Which is the longest river in Africa?", "opts": ["Congo", "Nile", "Zambezi", "Niger"], "a": 1},
        {"q": "How many US states are there?", "opts": ["48", "49", "50", "51"], "a": 2},
        {"q": "The Statue of Liberty was a gift from which country?", "opts": ["UK", "France", "Spain", "Italy"], "a": 1},
        {"q": "Which country has the most population?", "opts": ["China", "USA", "India", "Indonesia"], "a": 2},
        {"q": "What is the smallest continent by area?", "opts": ["Europe", "Australia/Oceania", "Antarctica", "South America"], "a": 1},
        {"q": "Which sea is between Europe and Africa?", "opts": ["Red Sea", "Mediterranean Sea", "Caspian Sea", "Black Sea"], "a": 1},
        {"q": "In which country is Machu Picchu?", "opts": ["Mexico", "Peru", "Chile", "Bolivia"], "a": 1},
        {"q": "Which is the world's largest island?", "opts": ["Australia", "Greenland", "New Guinea", "Madagascar"], "a": 1},
        {"q": "The Eiffel Tower is in?", "opts": ["London", "Rome", "Paris", "Berlin"], "a": 2},
        {"q": "Which African country has the largest economy?", "opts": ["Egypt", "South Africa", "Nigeria", "Kenya"], "a": 2},
    ],
}
